export const ISO3_TO_2 = {
  ABW:"aw",AFG:"af",AGO:"ao",AIA:"ai",ALB:"al",AND:"ad",ARE:"ae",ARG:"ar",
  ARM:"am",ASM:"as",ATG:"ag",AUS:"au",AUT:"at",AZE:"az",BDI:"bi",BEL:"be",
  BEN:"bj",BFA:"bf",BGD:"bd",BGR:"bg",BHR:"bh",BHS:"bs",BIH:"ba",BLR:"by",
  BLZ:"bz",BMU:"bm",BOL:"bo",BRA:"br",BRB:"bb",BRN:"bn",BTN:"bt",BWA:"bw",
  CAF:"cf",CAN:"ca",CHE:"ch",CHL:"cl",CHN:"cn",CIV:"ci",CMR:"cm",COD:"cd",
  COG:"cg",COK:"ck",COL:"co",COM:"km",CPV:"cv",CRI:"cr",CUB:"cu",CUW:"cw",
  CYP:"cy",CZE:"cz",DEU:"de",DJI:"dj",DMA:"dm",DNK:"dk",DOM:"do",DZA:"dz",
  ECU:"ec",EGY:"eg",ERI:"er",ESP:"es",EST:"ee",ETH:"et",FIN:"fi",FJI:"fj",
  FLK:"fk",FRA:"fr",FRO:"fo",FSM:"fm",GAB:"ga",GBR:"gb",GEO:"ge",GHA:"gh",
  GIN:"gn",GMB:"gm",GNB:"gw",GNQ:"gq",GRC:"gr",GRD:"gd",GRL:"gl",GTM:"gt",
  GUM:"gu",GUY:"gy",HKG:"hk",HND:"hn",HRV:"hr",HTI:"ht",HUN:"hu",IDN:"id",
  IND:"in",IRL:"ie",IRN:"ir",IRQ:"iq",ISL:"is",ISR:"il",ITA:"it",JAM:"jm",
  JOR:"jo",JPN:"jp",KAZ:"kz",KEN:"ke",KGZ:"kg",KHM:"kh",KIR:"ki",KNA:"kn",
  KOR:"kr",KWT:"kw",LAO:"la",LBN:"lb",LBR:"lr",LBY:"ly",LCA:"lc",LIE:"li",
  LKA:"lk",LSO:"ls",LTU:"lt",LUX:"lu",LVA:"lv",MAC:"mo",MAR:"ma",MCO:"mc",
  MDA:"md",MDG:"mg",MDV:"mv",MEX:"mx",MHL:"mh",MKD:"mk",MLI:"ml",MLT:"mt",
  MMR:"mm",MNE:"me",MNG:"mn",MOZ:"mz",MRT:"mr",MUS:"mu",MWI:"mw",MYS:"my",
  NAM:"na",NCL:"nc",NER:"ne",NGA:"ng",NIC:"ni",NLD:"nl",NOR:"no",NPL:"np",
  NRU:"nr",NZL:"nz",OMN:"om",PAK:"pk",PAN:"pa",PER:"pe",PHL:"ph",PLW:"pw",
  PNG:"pg",POL:"pl",PRI:"pr",PRK:"kp",PRT:"pt",PRY:"py",QAT:"qa",ROU:"ro",
  RUS:"ru",RWA:"rw",SAU:"sa",SDN:"sd",SEN:"sn",SGP:"sg",SLB:"sb",SLE:"sl",
  SLV:"sv",SMR:"sm",SOM:"so",SRB:"rs",STP:"st",SUR:"sr",SVK:"sk",SVN:"si",
  SWE:"se",SWZ:"sz",SYC:"sc",SYR:"sy",TCD:"td",TGO:"tg",THA:"th",TJK:"tj",
  TKM:"tm",TLS:"tl",TON:"to",TTO:"tt",TUN:"tn",TUR:"tr",TUV:"tv",TWN:"tw",
  TZA:"tz",UGA:"ug",UKR:"ua",URY:"uy",USA:"us",UZB:"uz",VCT:"vc",VEN:"ve",
  VNM:"vn",VUT:"vu",WSM:"ws",YEM:"ye",ZAF:"za",ZMB:"zm",ZWE:"zw",
};

export const EN_COUNTRIES = new Set([
  "US","GB","AU","CA","NZ","IE","NG","KE","GH","ZA","SG","PH","IN","PK","JM",
  "TT","BZ","GY","BB","BS","AG","DM","GD","KN","LC","VC","FJ","SB","VU","TO",
  "WS","KI","NR","TV","PW","MH","FM","CK","NF","AI","BM","FK","GI","MS","SH",
  "TC","VG","VI","AS","GU","PR","MP",
]);
